#!/usr/bin/osascript

tell application "System Events"
	set isMailRunning to (count of (every process whose bundle identifier is "com.apple.mail")) > 0
end tell
if isMailRunning then
	quit application "Mail" saving yes
	say "Mail restarting!"
	tell application "Mail" to activate
end if