#!/usr/bin/perl 
# a little script to get your network status 

$en0_info = `ifconfig en0 | grep "inet" | grep -v 127.0.0.1`; 
$en1_info = `ifconfig en1 | grep "inet" | grep -v 127.0.0.1`; 
$ext_info = `curl --silent http://checkip.dyndns.org | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'`;
$airport_network = `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | awk -F: '/ SSID: / {print $2}' | sed -e 's/.*SSID: //'`; 

if($ext_info) { 
	$output .= "External : $ext_info"; 
} 

if($en0_info) { 
	$en0_info =~ /inet (.*) netmask/s; 
	$output .= "Ethernet : $1 \n"; 
}


if($en1_info) { 
	$en1_info =~ /inet (.*) netmask/s; 
	$en1_info = $1; 
	$output .= "Airport :  $en1_info \n";
	$output .= "SSID :     $airport_network"; 
} 

print "$output";